apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: art-build-failures
  name: art-build-failures
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: art-build-failures:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/openshift-eng/art-dashboard-ui.git
      ref: art-build-failures
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: docker/Dockerfile
      from:
        kind: ImageStreamTag
        name: art-build-failures:base
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
      from:
        kind: ImageStreamTag
        name: art-build-failures:base
    type: ImageChange
